services:
  courtbooking.server:
    image: ${DOCKER_REGISTRY-}courtbookingserver
    build:
      context: .
      dockerfile: CourtBooking.Server/Dockerfile
    volumes:
      - ./data:/app
    ports:
      - "32771:8081"  # HostPort:ContainerPort (8081 is your container's HTTPS port)
      - "5002:8080"   # Optional: HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080